# Generated by Django 4.1.7 on 2023-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0002_alter_roommatepreference_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommatepreference',
            name='rent',
            field=models.CharField(max_length=20),
        ),
    ]
