# Generated by Django 4.1.7 on 2023-03-21 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching_app', '0003_alter_roommatepreference_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommatePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='lifestyle',
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='age_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='age_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='layout',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='location',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='occupation',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='room_size',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='purpose',
            field=models.ManyToManyField(to='matching_app.roommatepurpose'),
        ),
    ]
