# Generated by Django 4.1.7 on 2023-03-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0005_purpose_delete_roommatepurpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommatepreference',
            name='purpose',
            field=models.ManyToManyField(to='matching_app.purpose', verbose_name='目的'),
        ),
    ]
