# Generated by Django 4.1.7 on 2023-03-25 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching_app', '0006_alter_roommatepreference_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommatepreference',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='location',
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='room_size',
        ),
        migrations.AddField(
            model_name='purpose',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purpose', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='commute_time',
            field=models.CharField(default=1, max_length=10, verbose_name='通勤時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='parking',
            field=models.CharField(default=1, max_length=10, verbose_name='駐車場'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='period',
            field=models.CharField(default=1, max_length=10, verbose_name='期間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='pet',
            field=models.CharField(default=1, max_length=10, verbose_name='ペット'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='prefecture',
            field=models.CharField(default=1, max_length=10, verbose_name='都道府県'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=50, verbose_name='目的名'),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='age_max',
            field=models.IntegerField(verbose_name='最大年齢'),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='age_min',
            field=models.IntegerField(verbose_name='最小年齢'),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='性別'),
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='layout',
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='occupation',
            field=models.CharField(max_length=10, verbose_name='職業'),
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='rent',
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='smoking',
            field=models.CharField(max_length=10, verbose_name='喫煙'),
        ),
        migrations.CreateModel(
            name='RoomLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=10, verbose_name='間取り')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_layout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.CharField(max_length=20, verbose_name='家賃')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesiredCohabitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='人数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desired_cohabitee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='desired_cohabitee',
            field=models.ManyToManyField(to='matching_app.desiredcohabitee', verbose_name='同居人数'),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='layout',
            field=models.ManyToManyField(to='matching_app.roomlayout', verbose_name='間取り'),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='rent',
            field=models.ManyToManyField(to='matching_app.rent', verbose_name='家賃'),
        ),
    ]
