# Generated by Django 4.1.7 on 2023-03-26 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching_app', '0007_remove_roommatepreference_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purpose',
            old_name='name',
            new_name='purpose_name',
        ),
        migrations.RemoveField(
            model_name='desiredcohabitee',
            name='number',
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='desired_cohabitee',
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='rent',
        ),
        migrations.AddField(
            model_name='desiredcohabitee',
            name='cohabitation_number',
            field=models.IntegerField(default=1, verbose_name='同居人数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desiredcohabitee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_cohabitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent',
            field=models.CharField(max_length=30, verbose_name='家賃'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomlayout',
            name='layout',
            field=models.CharField(max_length=30, verbose_name='間取り'),
        ),
        migrations.AlterField(
            model_name='roomlayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_layout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
