# Generated by Django 4.1.7 on 2023-03-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0008_rename_name_purpose_purpose_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredcohabitee',
            name='cohabitation_number',
            field=models.CharField(max_length=30, verbose_name='同居人数'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='purpose_name',
            field=models.CharField(max_length=200, verbose_name='目的名'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent',
            field=models.CharField(max_length=100, verbose_name='家賃'),
        ),
        migrations.AlterField(
            model_name='roomlayout',
            name='layout',
            field=models.CharField(max_length=50, verbose_name='間取り'),
        ),
    ]
