# Generated by Django 4.1.7 on 2023-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0009_alter_desiredcohabitee_cohabitation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommatepreference',
            name='age_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大年齢'),
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='age_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='最小年齢'),
        ),
    ]
