# Generated by Django 4.1.7 on 2023-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_userprofile_age_remove_userprofile_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default_images/default_profile.jpg', upload_to='profile_images/'),
        ),
    ]
