# Generated by Django 4.1.7 on 2023-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroomlayout',
            name='layout',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
