# Generated by Django 4.1.7 on 2023-04-01 15:23

from django.db import migrations, models
import messages_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=messages_app.models.unique_file_path),
        ),
    ]
